In [2]:
import torch

In [39]:
q_values = [[0.5, 0.2], [1.2, 0.7], [1.9, 0.3]]
actions = [1, 0, 1]

print(q_values)
print(actions)

[[0.5, 0.2], [1.2, 0.7], [1.9, 0.3]]
[1, 0, 1]


In [46]:
q_values = torch.tensor(q_values)
actions = torch.tensor(actions)

/var/folders/jq/9y7v6qbd06g8j3w_t6v0pxl80000gn/T/ipykernel_27442/3688498030.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  q_values = torch.tensor(q_values)
/var/folders/jq/9y7v6qbd06g8j3w_t6v0pxl80000gn/T/ipykernel_27442/3688498030.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  actions = torch.tensor(actions)


In [49]:
print(q_values)
print(q_values.shape)
print('---')
print(actions)
print(actions.shape)

tensor([[0.5000, 0.2000],
        [1.2000, 0.7000],
        [1.9000, 0.3000]])
torch.Size([3, 2])
---
tensor([1, 0, 1])
torch.Size([3])


In [60]:
actions.unsqueeze(1)

tensor([[1],
        [0],
        [1]])

In [63]:
q_values.gather(1, actions.unsqueeze(1))

tensor([[0.2000],
        [1.2000],
        [0.3000]])